### ISSUE TITLE
Unable to communicate with Rltracker

### ISSUE THREAD

**Issue by misterdrprof** [IronFlare/Trading-Verifier-Docs#1]
Will not display anyone as scammer or clean, I'm greeted with this box for everyone: https://i.imgur.com/sdWXIsm.png

Also Luckey's profile doesnt even show a box: https://gfycat.com/GleamingFrighteningAmericanbulldog

Rltracker is up, uninstalling and reinstalling  fixes nothing, as does disabling it and re-enabling it.

**Comment by IronFlare** [comment]
Content script and background page aren’t throwing errors. This may branch into two issues—Luckey’s page specifically, and access to RLTracker. Check if the DOM differs for Luckey’s page, or if window vars are missing.

**Comment by JacksonGolletz** [comment]
My access to the RLTracker database has been revoked. The extension no longer has the ability to make queries, which is kind of the point of the extension. Actively working to determine the issue and resolve.

**Comment by IronFlare** [comment]
My API access to the RLTracker database has been revoked. In other words, the extension can no longer check users, which is kind of the whole point of the extension. I'm actively working to determine the issue and resolve.

**Comment by IronFlare** [comment]
Yixn has revoked my access due to a stylistic change made to the extension. "RLTracker" is still displayed prominently on almost every message along with a link. But Yixn's going to bed now, so the extension is dead.

**Comment by IronFlare** [comment]
Migrated embed display issues to #2.

**Comment by IronFlare** [comment]
Resolved in [version 1.1.2](https://github.com/IronFlare/Trading-Verifier-Docs/wiki/Version-1.1.2).
