### ISSUE TITLE
Trading verifier not pulling info from the RLtracker database

### ISSUE THREAD

**Issue by LightsTC** [IronFlare/Trading-Verifier-Docs#4]
Getting this everytime you attempt to check somebody's Steam profile: "The RLTracker database didn't respond in time. Please wait one minute, then try again." https://i.imgur.com/qVm5nMD.png

**Comment by IronFlare** [comment]
This is an issue with RLTracker's servers — from around 19:00 until 19:40 this evening (GMT-7), the site was not responding to any requests, including those from the extension.
